// <auto-generated />
namespace AutoInsuranceWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCourierCompanyMaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCourierCompanyMaster));
        
        string IMigrationMetadata.Id
        {
            get { return "201710051400171_add-CourierCompanyMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
